apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gatekeeper-metric
  namespace: gatekeeper-system
  labels:
    release: prometheus # Make sure this matches Prometheus' selector
spec:
  selector:
    matchLabels:
      gatekeeper.sh/system: "yes"
  podMetricsEndpoints:
    - portNumber: 8888
      path: /metrics
      interval: 5s
    - port: metrics
      path: /metrics
      interval: 5s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: opa-exporter
  namespace: opa-exporter
  labels:
    release: prometheus # Make sure this matches Prometheus' selector
spec:
  selector:
    matchLabels:
      app: opa-exporter
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 5s
