apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NsPodRequired
metadata:
  name: ns-pod-req
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    labels: ["owner"]
