apiVersion: constraints.gatekeeper.sh/v1beta1
kind: UniqueLabelsPod
metadata:
  name: unique-owner
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    label: "owner"
    namespaces: ["test"]
