apiVersion: constraints.gatekeeper.sh/v1beta1
kind: LimitedReplica
metadata:
  name: limit-five
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces:
      - test
      - default
  parameters:
    max: 5
