apiVersion: mutations.gatekeeper.sh/v1
kind: AssignMetadata
metadata:
  name: add-label-admin
spec:
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
  location: "metadata.labels.owner"
  parameters:
    assign:
      value:  "admin"
